---
name: action_when_pull_request_happens_to_main

on:
  pull_request:
    branches:
      - main
    paths:
      - "infra/*"

jobs:
  cdk_snapshot:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install_node
        uses: actions/setup-node@v4
        with:
          node-version: 22